# Generated by Django 4.1 on 2022-08-30 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator(
                        message="Недопустимое значение поля."
                    )
                ],
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Недопустимое значение поля.", regex="^[\\w.@+-]+$"
                    )
                ],
                verbose_name="Логин",
            ),
        ),
    ]
