name: foodgram_api_dev pipeline

on: [push]

jobs:
  backend_dev_test_new_commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run python3 setup
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: run dependencies installation
      run: | 
        python -m pip install --upgrade pip 
        cd backend/foodgram_api
        pip install -r requirements.txt 
    - name: run linting and unit testing
      run: |
        python -m flake8
        pytest

  backend_dev_deliver_to_docker_hub:
    name: run foodgram_api_dev image to docker hub delivery
    runs-on: ubuntu-latest
    needs: backend_dev_test_new_commit

    steps:
    - name: run check-out the repository
      uses: actions/checkout@v2 
    - name: run docker buildx setup
      uses: docker/setup-buildx-action@v1 
    - name: run docker login 
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: run foodgram_api_dev image push to docker hub
      uses: docker/build-push-action@v2 
      with:
        file: backend/foodgram/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_api_dev:latest
  
  backend_dev_deploy_to_remote_host:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: backend_dev_deliver_to_docker_hub

    steps:
    - name: run foodgram_api_dev image deploy to remote host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd foodgram
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/foodgram_api_dev:latest
          sudo docker-compose images

  backend_dev_notify_to_telegram:
    runs-on: ubuntu-latest
    needs: backend_dev_deploy_to_remote_host

    steps:
    - name: run foodgram_api_dev image success deploy notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} success